name: f58_app_jam_project
description: OUA App Jam Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.4

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "FFCC00"
  image: "assets/oua_background.png"

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/icerik.png